name: build backend

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  test:
    defaults:
      run:
        working-directory: ./server-backend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3.9.1
        with:
          node-version-file: .nvmrc

      - name: Install packages
        run: npm ci

      - name: Run tests
        run: npm run test
